import numpy as np

# Labels definition
PATIENT_LABEL_UNKNOWN = 5
PATIENT_LABEL_NON_AF = 0
PATIENT_LABEL_AF_MILD = 1
PATIENT_LABEL_AF_MODERATE = 2
PATIENT_LABEL_AF_SEVERE = 3
PATIENT_LABEL_OTHER_CVD = 4

PATIENT_LABELS = np.array([PATIENT_LABEL_NON_AF, PATIENT_LABEL_AF_MILD, PATIENT_LABEL_AF_MODERATE,
                           PATIENT_LABEL_AF_SEVERE, PATIENT_LABEL_OTHER_CVD, PATIENT_LABEL_UNKNOWN])

# Constants definitions (time related)
N_S_IN_HOUR = 3600
N_MS_IN_S = 1000
N_HOURS_IN_DAY = 24
N_MIN_IN_HOUR = 60
N_SEC_IN_MIN = 60
